# Generated by Django 5.1 on 2024-09-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Place_app', '0001_initial'),
        ('User_app', '0003_jabamausers_delete_jabamauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Place_app.advertisement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User_app.jabamausers')),
            ],
        ),
    ]
