# Generated by Django 5.1 on 2024-09-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
